service: simple-graphql

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-north-1
  memorySize: 128
  timeout: 3

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-typescript

functions:
  graphql:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
